const details = [
    {
        position: "Product Designer",
        work: [
            "First Product Designer at Tuist, establishing and leading design initiatives from the ground up.",
            "Creating Noora, an accessible and scalable design system and style guide for CLI and dashboard to ensure consistency and efficiency in product development.",
            "Designing a developer dashboard tailored for the Apple app development ecosystem.",
            "Spearheading brand revamp, including the company’s branding, website, and key marketing assets.",
        ],
        company: "Tuist",
        companyLink: "https://tuist.dev",
        time: "12, 2024 - Present",
        address: "Germany (Hybrid)",
        color: "#1A004B",
        bgcolor: "#F4F4FF",
    },
    {
        position: "Product Designer",
        work: [
            "First product designer at Biorce, spearheading design initiatives from the ground up.",
            "Built an accessible, scalable design system and style guide from the ground up, enabling consistency and efficiency in product development.",
            "Played a critical role in the creation of Jarvis, Biorce's AI-powered flagship product, by designing the MVP to meet complex user needs in the healthcare sector.",
            "Led efforts in the redesign of the company website for a more cohesive user experience.",
        ],
        company: "Biorce",
        companyLink: "https://www.biorce.com/",
        time: "03, 2024 - 12, 2024",
        address: "Spain (Remote)",
        color: "#001A4F",
        bgcolor: "#E1FBFF",
    },
    {
        position: "UX Intern",
        work: [
            "Developed prototypes and wireframes for intricate JSON components.",
            "Performed user research to refine methods for visually presenting AsyncAPI specification, aimed at improving user experience and accessibility.",
            "Contributed to the design of generated documentation by simplifying JSON Schema representation, enhancing the visual design of AsyncAPI files and event-driven architecture.",
            "Collaborated with the founder, lead designer and stakeholders to strategize plans for upcoming releases.",
        ],
        company: "AsyncAPI",
        companyLink: "https://www.asyncapi.com/",
        time: "06, 2023 - 02, 2024",
        address: "Spain (Remote)",
        color: "#540062",
        bgcolor: "#FFEEFD",
    },
    {
        position: "UX/UI Intern",
        work: [
            "Conducted user research, met the needs for 200+ monthly users by developing a website more suited to user needs by increasing responsiveness and optimizing navigation.",
            "Designed high fidelity working prototypes and implemented a comprehensive design system from scratch, increasing consistency across the organization.",
            "Created an accessible design system that met Web Content Accessibility Guidelines 2.0 and AAA compliance, by focusing on color contrast, typography, and layouts.",
        ],
        company: "conda-forge",
        companyLink: "https://conda-forge.org/",
        time: "05, 2023 - 09, 2023",
        address: "Germany (Remote)",
        color: "#00695C",
        bgcolor: "#D2FFFB",
    },
    {
        position: "UX/UI Mentor",
        work: [
            "Pioneered on designing a new web portal and refactoring of the ORAS documentation.",
            "Led the design initiative throughout the project lifecycle, ensuring a sustained focus on innovative and user-centric solutions.",
            "Collaborated with mentees to learn and enhance their technical skills.",
        ],
        company: "ORAS Project",
        companyLink: "https://oras.land/",
        time: "05, 2023 - 08, 2023",
        address: "California (Remote)",
        color: "#7C4300",
        bgcolor: "#FDF9EF",
    },
    {
        position: "Visual Design Intern",
        work: [
            "Commenced the work on design system and collaborated on high fidelity prototypes with engineers, and a new design system including typography, and layouts.",
            "Carried out user research studies with maintainers and users, identifying key pain points and informed product design decisions.",
            "Integrated aforementioned studies to develop a new consumer website, increasing user interaction by 80%.",
            "Drove an impressive 50% performance improvement and a substantial 70% SEO boost.",
        ],
        company: "ORAS Project",
        companyLink: "https://oras.land/",
        time: "03, 2023 - 05, 2023",
        address: "California (Remote)",
        color: "#00397C",
        bgcolor: "#EFF5FD",
    },
    {
        position: "Frontend Intern",
        work: [
            "Facelifted the design of Faces of GNOME, a community platform to show the contributions made by 1000+ GNOME developers.",
            "Identified and addressed design-related front-end bugs, renewed vector graphics of all pages.",
            "Leveraged JavaScript and Jekyll for frontend engineering primarily.",
        ],
        company: "GNOME Foundation",
        companyLink: "https://foundation.gnome.org/",
        time: "06, 2022 - 10, 2022",
        address: "Germany (Remote)",
        color: "#006D7C",
        bgcolor: "#EFFCFD",
    },
    {
        position: "Technical Writing Intern",
        work: [
            "Authored 10+ user guides to help newcomers get started with contributing to Weaviate.",
            "Facilitated the successful migration from Jekyll to Docusaurus, improving build efficiency by 80% for the organization.",
        ],
        company: "Weaviate",
        companyLink: "https://weaviate.io/",
        time: "05, 2022 - 12, 2022",
        address: "Netherlands (Remote)",
        color: "#00931D",
        bgcolor: "#ECFFE9",
    },
];

export default { details };
